# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-23 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_remove_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic_url',
            field=models.CharField(default='', max_length=800),
        ),
    ]
