# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-23 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0003_userprofile_profile_pic_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_vip',
        ),
    ]
